### ISSUE TITLE
Client issue

### ISSUE THREAD

**Issue by damon-kwok** [Suprcode/mir2#860]
[20/9/2023 16:57:26] System.TypeInitializationException: The type initializer for 'Client.MirControls.MirScene' threw an exception.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at SlimDX.ComObject.get_UnknownPointer() in c:\users\promit\documents\projects\slimdx\main\trunk\source\comobject.cpp:line 71
   at SlimDX.Direct3D9.Texture..ctor(Device device, Int32 width, Int32 height, Int32 levelCount, Usage usage, Format format, Pool pool) in c:\users\promit\documents\projects\slimdx\main\trunk\source\direct3d9\texture.cpp:line 50
   at Client.MirGraphics.MImage.CreateTexture(BinaryReader reader) in D:\mir2\Client\MirGraphics\MLibrary.cs:line 897
   at Client.MirGraphics.MLibrary.GetTrueSize(Int32 index) in D:\mir2\Client\MirGraphics\MLibrary.cs:line 620
   at Client.MirControls.MirImageControl.get_Size() in D:\mir2\Client\MirControls\MirImageControl.cs:line 148
   at Client.MirScenes.LoginScene.LoginDialog..ctor() in D:\mir2\Client\MirScenes\LoginScene.cs:line 334
   at Client.MirScenes.LoginScene..ctor() in D:\workspace\mir2\Client\MirScenes\LoginScene.cs:line 43
   at Client.MirControls.MirScene..cctor() in D:\workspace\mir2\Client\MirControls\MirScene.cs:line 11
   --- End of inner exception stack trace ---
   at Client.CMain.CMain_MouseMove(Object sender, MouseEventArgs e) in D:\mir2\Client\Forms\CMain.cs:line 178

**Comment by Suprcode** [comment]
Please specify how you replicate this error
